[project]
name = "vim"
version = "0.1.0"
dependencies = ["pynvim>=0.5.2", "pip>=25.1.1", "ruff>=0.15.12", "ty>=0.0.34"]
requires-python = ">=3.12,<3.13"

[tool.uv]
managed = true
exclude-newer = "10 days"

[tool.uv.workspace]
members = []

[tool.setuptools]
py-modules = []

# Development checks:
# ./manage check
# ./manage check --fix
