[project]
name = "vim"
version = "0.1.0"
requires-python = ">=3.12,<3.15"
dependencies = ["pip>=25.1.1", "pynvim>=0.5.2", "ruff>=0.15.12", "ty>=0.0.34"]

[dependency-groups]
dev = ["semgrep>=1.90.0"]

[tool.setuptools]
py-modules = []

[tool.uv]
managed = true
exclude-newer = "10 days"

[tool.uv.workspace]
members = []
