#!/usr/bin/env bash
#
# @import console/info
# @description clean all vim bundles

main () {
    strict  true
    verbose true

    local path
    local dir
    path="$HOME/.vim/bundle"
    local OPWD=$PWD ; cd "${path}" || exit
    for dir in "${path}"/*
    do
        if [ -d "${dir}" ]
        then
            _ info "Removing $(basename "${dir}")"
            rm -rf "${dir}"
        fi
    done
    [ -e "$HOME/.vim/.ready" ] && rm -f "$HOME/.vim/.ready"
    cd "${OPWD}" || exit
    touch "$HOME/.vim/vimrc"
}

