#!/usr/bin/env bash
#
# @description install vim/nvim bundles
# @import lang/exists

main () {
    strict  true
    verbose true

    [ -d "$HOME/.vim-dist/bin/" ] && PATH="$HOME/.vim-dist/bin:$PATH"
    [ -d "$HOME/.neovim-dist/bin/" ] && PATH="$HOME/.neovim-dist/bin:$PATH"

    local executable="vim"

    if _ exists nvim
    then
        executable="nvim"
    fi

    if [ -d "${MANAGE_REPOSITORY}" ] || [ -L "${MANAGE_REPOSITORY}" ]; then
        local path
        path="${MANAGE_REPOSITORY}"
        local OPWD=$PWD ; cd "${path}" || exit

        git submodule update --init --recursive

        cd "${path}" || exit

        if [[ "${executable}" == "vim" ]]
        then
            "${executable}" -es -u vimrc -i NONE -c "PlugInstall!" -c "qa" || true
        fi

        if [[ "${executable}" == "nvim" ]]
        then
            "${executable}" -es -u init.vim  -c "PlugInstall!" -c "qa" || true
        fi

        touch "${MANAGE_REPOSITORY}/vimrc"

        mkdir -p "${HOME}/.config"

        if [[ ! -e "${HOME}/.config/nvim" ]]
        then
            ln -s "${MANAGE_REPOSITORY}" "${HOME}/.config/nvim"
        fi

        cd "${OPWD}" || exit
    fi
}

