#!/usr/bin/env bash
#
# @description update vim/nvim bundles
# @import console/die
# @import lang/exists

main () {
    strict  true
    verbose true

    [ -d "$HOME/.vim-dist/bin/" ] && PATH="$HOME/.vim-dist/bin:$PATH"
    [ -d "$HOME/.neovim-dist/bin/" ] && PATH="$HOME/.neovim-dist/bin:$PATH"

    local executable="vim"

    if _ exists nvim
    then
        executable="nvim"
    fi

    if [ -d "${MANAGE_REPOSITORY}" ] || [ -L "${MANAGE_REPOSITORY}" ]; then
            local path
            path="${MANAGE_REPOSITORY}"
            local OPWD=$PWD ; cd "${path}" || exit

            if [[ "${executable}" == "vim" ]]
            then
                "${executable}" -es -u vimrc -i NONE -c "PlugUpdate!" -c "qa" || true
            fi

            if [[ "${executable}" == "nvim" ]]
            then
                "${executable}" -es -u init.vim -i NONE -c "PlugUpdate!" -c "qa" || true
            fi

            cd "${OPWD}" || exit
            touch "${MANAGE_REPOSITORY}/vimrc"
            touch "${MANAGE_REPOSITORY}/.ready"
    fi
}

