name: test
on:
  push:
    branches:
      - trunk
  pull_request:
    branches:
      - trunk
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6
      - name: install the latest version of uv
        uses: astral-sh/setup-uv@v8
        with:
          cache-dependency-glob: |
            pyproject.toml
            uv.lock
            **/pyproject.toml
          enable-cache: true
          ignore-nothing-to-cache: true
          version: 'latest'
      - name: install node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
          package-manager-cache: false
      - name: install pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true
          cache_dependency_path: pnpm-lock.yaml
          run_install: false
      - name: dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt-get install zsh bc
            curl -sLO https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
            chmod u+x nvim.appimage
            mkdir -p "$HOME/.neovim-dist/bin"
            mv ./nvim.appimage "$HOME/.neovim-dist/bin/nvim"
          elif [ "$RUNNER_OS" == "macOS" ]; then
            brew install bash zsh bc gnu-sed
            brew install neovim --HEAD
            # mkdir -p "$HOME/.neovim-dist"
            # curl -sLO https://github.com/neovim/neovim/releases/download/nightly/nvim-macos.tar.gz
            # xattr -c nvim-macos.tar.gz
            # tar xzvf nvim-macos.tar.gz --strip-components=1 -C "$HOME/.neovim-dist"
            # rm -f nvim-macos.tar.gz
          fi
      - name: test
        run: |
          ln -s $(pwd) ~/.vim
          ~/.vim/manage install
